#!/usr/bin/env bash
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             dask-labextension
                            


#EOF