#!/usr/bin/env bash


if [ ! -d ~/.config/dask ]; then
  mkdir -p ~/.config/dask
fi

jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             dask-labextension



#EOF
