version: 2.1

jobs:
  test-py3:
    docker:
      - image: circleci/python:3.7


    steps:
      - checkout
      - run:
          name: Fresh conda install without existing environments
          command: |
            ./setup/configure

      - run:
          name: Running Tests
          command: |
            export PATH="$HOME/miniconda3/bin:$PATH"
            conda info
            source activate python-tutorial
            ./setup/check_setup

  test-py2:
    docker:
      - image: circleci/python:2.7

    steps:
      - checkout
      - run:
          name: Fresh conda install without existing environments
          command: |
            ./setup/configure


      - run:
          name: Running Tests
          command: |
            export PATH="$HOME/miniconda3/bin:$PATH"
            conda info
            source activate python-tutorial
            ./setup/check_setup

  test-conda:
    docker:
      - image: continuumio/miniconda3:latest


    steps:
      - checkout

      - run:
          name: Create env with existing conda installation
          command: |
            conda info
            ./setup/configure --clobber

      - run:
          name: Running Tests
          command: |
            conda info
            source activate python-tutorial
            ./setup/check_setup

workflows:
  version: 2
  default:
    jobs:
      - test-py3
      - test-py2
      - test-conda
