#!/usr/bin/env bash

set -xeo pipefail

export PATH="$INSTALL_DIR/bin:$PATH"

# Install jupyterlab extensions
source activate base
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @jupyterlab/toc \
                             dask-labextension

jupyter labextension update --all
