#!/bin/bash
set -e

#-- set defaults
# expected environment variables
if [ -z "${JOB_ACCOUNT}" ]; then
  source /glade/u/apps/ch/opt/usr/bin/getacct.sh
fi
job_account=${JOB_ACCOUNT}

walltime=06:00:00
queue=share
memory=8GB
notebook_dir=${HOME}
jlab_port=8888
#dash_port=8787

NODES=1
CORES=1
LOAD_MATLAB=
MATLAB_VERSION=R2018a

#-- define usage
usage () {
cat << EOF
Usage: launch dask
Possible options are:
 -a,--account: account
 -w,--walltime: walltime [default: ${walltime}]
 -q,--queue: queue [default: ${queue}]
 -m,--memory: memory request [default: ${memory}]
 -d,--directory: notebook directory
 -p,--port: [default: ${jlab_port}]
 --matlab: run matlab kernel
 --matlab-version: matlab version [default: ${MATLAB_VERSION}]
EOF
exit
}

#-- parse input args
while [[ $# -gt 0 ]]; do
  key="${1}"
  case ${key} in
    -h|--help)
      usage ;;
    -a|--account)
      job_account="${2}"
      shift 2
      ;;
    -w|--walltime)
      walltime="${2}"
      shift 2
      ;;
    -m|--memory)
      memory="${2}"
      shift 2
      ;;
    -q|--queue)
      queue="${2}"
      shift 2
      ;;
    -d|--directory)
      notebook_dir="${2}"
      shift 2
      ;;
    --add-workers)
      add_workers=true
      shift
      ;;
    -p|--port)
      jlab_port="${2}"
      shift 2
      ;;
    --matlab)
      LOAD_MATLAB=1
      shift
      ;;
    --matlab-version)
      MATLAB_VERSION="${2}"
      shift 2
      ;;
    *)
      echo "ERROR: unknown argument: ${key}"
      usage
      ;;
  esac
done

#-- check inputs
if [ -z "${walltime}" ]; then
  echo "ERROR: walltime not set."
  exit 1
fi
if [ -z "${queue}" ]; then
  echo "ERROR: queue not set."
  exit 1
fi
if [[ -z ${WORKDIR} ]]; then
    WORKDIR=/glade/scratch/${USER}/tmp
fi

#-- make sure the working directory exists
if [[ ! -d ${WORKDIR} ]]; then
  mkdir -vp ${WORKDIR}
fi
LOGFILE=${WORKDIR}/jlab-ch.jlab-log.$(date +%Y%m%dT%H%M%S)


if [ ! -z "${LOAD_MATLAB}" ]; then
  source activate py-matlab
  python_version=$(python --version | awk '{print $2}' | awk -F. '{print $1 "." $2}')
  MATLAB_API_PATH=~/matlab-python/${MATLAB_VERSION}/lib/python${python_version}/site-packages
  if [ ! -d ${MATLAB_API_PATH} ]; then
    MATLAB_API_PATH=~mclong/matlab-python/${MATLAB_VERSION}/lib/python${python_version}/site-packages
    if [ ! -d ${MATLAB_API_PATH} ]; then
      echo "ERROR:"
      echo "  Matlab API for ${MATLAB_VERSION} not found;"
      echo "  build API using build-matlab-api script:"
      echo "  >>> ./build-matlab-api ${MATLAB_VERSION}"
      exit 1
    fi
  fi
fi


echo "Launching notebook server"
if [ ! -z "${LOAD_MATLAB}" ]; then
  echo "  *Loading Matlab version: ${MATLAB_VERSION}*"
fi

echo "  queue = ${queue}"
echo "  account = ${job_account}"
echo "  nodes = ${NODES}"
echo "  ncpus = ${CORES}"
echo "  memory = ${memory}"
echo "  walltime = ${walltime}"
echo "  port = ${jlab_port}"
echo

s=$(qsub << EOF
#!/bin/bash
#PBS -N jlab-ch
#PBS -q ${queue}
#PBS -A ${job_account}
#PBS -l select=${NODES}:ncpus=${CORES}:mpiprocs=${CORES}:mem=${memory}
#PBS -l walltime=${walltime}
#PBS -o ${WORKDIR}/
#PBS -e ${WORKDIR}/
#PBS -j oe

# setup environment
module purge
unset LD_LIBRARY_PATH

# load matlab
if [ ! -z "${LOAD_MATLAB}" ]; then
  export PYTHONPATH=${MATLAB_API_PATH}
  module load matlab/${MATLAB_VERSION}
fi

# run lab server
cd ${notebook_dir}
jupyter lab --no-browser --notebook-dir ${notebook_dir} --ip=\$(hostname) >& ${LOGFILE}
EOF
)
sjob=${s%.*}
echo "submitted job: ${sjob} to queue ${queue}"

trap ctrl_c INT
function ctrl_c() {
  echo "killing ${sjob}"
  qdel ${sjob}
  exit 0
}


#-- wait for job to start
echo -n "waiting for job to run"
while [ 1 ]; do
  #-- get job status
  job_state=$(qstat -x -f ${sjob} | grep job_state | awk -F= '{print $2}')
  exec_host=$(qstat -x -f ${sjob} | grep exec_host | awk -F= '{print $2}')

  if [[ -n "${exec_host}" && ${job_state} =~ R ]]; then
    exec_host=$(echo -e "${exec_host%/*}" | tr -d '[:space:]')
    echo .
    echo "Job ID: ${sjob}"
    echo "Job host: ${exec_host}"
    break
  elif [[ ${job_state} =~ F ]]; then
    echo "Job failed."
    qstat -x -f ${sjob}
    exit 1
  else
    echo -n ..
  fi
  sleep 1
done

#-- wait until log file is there
echo "waiting for job log to appear: ${LOGFILE}"
while [ ! -f "${LOGFILE}" ]; do
  sleep 1
done

#-- wait until address shows up in log
ADDRESS=
ELAPSED=0
while [ -z "${ADDRESS}" ]; do
  ADDRESS=$(grep -e '^\[.*\]\s*http://.*:' ${LOGFILE} | head -n 1)
  PORT=$(echo ${ADDRESS#*http://} | awk -F':' '{print $2}' | awk -F'/' '{print $1}')
  sleep 1
  ((ELAPSED+=1))
  if [[ ${ELAPSED} -gt 120 ]]; then
      echo -e "something went wrong\n---"
      cat ${LOGFILE}
      echo "---"
      ctrl_c
  fi
done

echo
echo "----------------------------------------------------------------------"
echo "Execute on local machine:"
echo "ssh -N -L ${jlab_port}:${exec_host}:${PORT} ${USER}@$(hostname).ucar.edu" # -L ${dash_port}:${exec_host}:8787
echo
echo "Open a browser on your local machine and type in the address bar:"
echo "http://localhost:${jlab_port}"
echo "----------------------------------------------------------------------"
echo

echo "Job log: ${LOGFILE}"
tail -f ${LOGFILE}
