#!/usr/bin/env python3
import importlib


def check_conda():
    from distutils.spawn import find_executable

    return find_executable("conda") is not None


def main():

    assert check_conda()

    required_modules = [
        "numpy",
        "dask",
        "xarray",
        "matplotlib",
        "cartopy",
        "jupyter",
        "zarr",
        "ipywidgets",
    ]
    missing_modules = []
    for mod in required_modules:
        try:
            importlib.import_module(mod)

        except ImportError:
            missing_modules.append(mod)

    if missing_modules:
        print("The following modules are required but not installed:")
        print("    {}".format(", ".join(missing_modules)))
        print("\nYou can install them using conda by running:")
        print("\n    conda install {}".format(" ".join(missing_modules)))
        print("\nOr you can install them using pip by running:")
        print("\n    pip install {}".format(" ".join(missing_modules)))

    else:
        print("Everything looks good!")


if __name__ == "__main__":
    main()
