#!/usr/bin/env python3
import importlib

# from pathlib import Path


def check_conda():
    from distutils.spawn import find_executable

    return find_executable("conda") is not None


def main():

    try:
        assert check_conda()
    except AssertionError:
        raise AssertionError("Conda binary is missing from $PATH")

    required_modules = [
        "numpy",
        "dask",
        "xarray",
        "matplotlib",
        "cartopy",
        "jupyter",
        "zarr",
        "ipywidgets",
    ]
    missing_modules = []
    for mod in required_modules:
        try:
            importlib.import_module(mod)

        except ImportError:
            missing_modules.append(mod)

    # cartopy_assets = Path("~/.local/share/cartopy").expanduser()
    # try:
    #     assert cartopy_assets.exists()
    # except AssertionError:
    #     raise AssertionError("Cartopy plotting assets are missing")

    if missing_modules:
        print("The following modules are required but not installed:")
        print("    {}".format(", ".join(missing_modules)))
        print("\nYou can install them using conda by running:")
        print("\n    conda install {}".format(" ".join(missing_modules)))
        print("\nOr you can install them using pip by running:")
        print("\n    pip install {}".format(" ".join(missing_modules)))

    else:
        print("Everything looks good!")


if __name__ == "__main__":
    main()
