#!/usr/bin/env bash

set -xeo pipefail

export PATH="$INSTALL_DIR/bin:$PATH"

# Add conda-forge and activate strict
conda config --add channels conda-forge
conda config --set channel_priority strict
conda config --set show_channel_urls True

conda update -q conda
conda env update -q -f $BASE_ENV_YML
conda env update -q -f $ANALYSIS_ENV_YML


conda info -a

if [ -z "$INIT_SHELL" ]; then
   echo "INIT_SHELL is unset. Skipping conda init INIT_SHELL";
else
  conda init $INIT_SHELL;
fi
