#!/usr/bin/env bash

set -xeo pipefail

wget $INSTALLER -O miniconda.sh
chmod +x miniconda.sh
./miniconda.sh -b -p $INSTALL_DIR
export PATH="$INSTALL_DIR/bin:$PATH"
conda config --add channels conda-forge

conda env update -f $BASE_ENV_YML
conda env update -f $ANALYSIS_ENV_YML

conda info -a
