#!/usr/bin/env bash

set -xeo pipefail

export PATH="$INSTALL_DIR/bin:$PATH"

# Install jupyterlab extensions

source activate python-tutorial
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             nbdime-jupyterlab \
                             jupyter-leaflet


jupyter labextension update --all


if [ "$(ls -A ~/.local/share/cartopy)" ]; then
   echo "Cartopy plotting assets exist already"

else
    # Download Cartopy plotting assets
    mkdir -p ~/.local/share/cartopy
    python $CARTOPY_ASSET_SCRIPT --output ~/.local/share/cartopy cultural-extra cultural gshhs physical
fi

# removes tarballs and unused packages
conda clean -tipsy
