#!/usr/bin/env bash

set -xeo pipefail

export PATH="$INSTALL_DIR/bin:$PATH"

# Install jupyterlab extensions
conda activate base
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             dask-labextension \
                             jupyterlab-nvdashboard

jupyter labextension update --all && jupyter labextension list

conda activate analysis
jupyter labextension install @jupyter-widgets/jupyterlab-manager \
                             @pyviz/jupyterlab_pyviz \
                             nbdime-jupyterlab



jupyter labextension update --all && jupyter labextension list
# Download Cartopy plotting assets
python $CARTOPY_ASSET_SCRIPT --output ~/.local/share/cartopy cultural-extra cultural gshhs physical
